# Generated by Django 5.1.6 on 2025-05-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_store_custo_first_n_a7e990_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL("""  
            INSERT INTO store_collection(title)
            VALUES ('collection 1')
""", """
            DELETE FROM store_collection
            WHERE title = 'collection 1'""")
    ]
